### ISSUE TITLE
Make chains immutable

### ISSUE THREAD

**Issue by urmaul** [crocodile2u/chainy#5]
You could add immutability easily by making `add()` return new instance of chain instead of `$this`.

**Comment by crocodile2u** [comment]
Hmm, that's definitely an option! And it does not look like a BC break at all! I
hope I'll have time to get to chainy on weekend!

чт, 15 нояб. 2018 г. в 15:03, Bogdan Kolbik <notifications@github.com>:

**Comment by crocodile2u** [comment]
https://github.com/crocodile2u/chainy/pull/7
